<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerLab.Domain\PowerLab.Domain.csproj" />
    <ProjectReference Include="..\PowerLab.Plugin.Abstractions\PowerLab.Plugin.Abstractions.csproj" />
  </ItemGroup>

</Project>
